const img = [
  {
    id: 1,
    logo: "./images/IONIQ5big.png",
    image: "./images/logo_IONIQ5.png",
    title: "현대자동차",
    desc: "IONIQ5 페이지 - 좋아하는 차량의 소개하는 페이지를 css flex, position, 폰트바꾸는 연습을 한 페이지입니다.",
    site: "https://eunki0916.github.io/ioniq5/",
  },
  {
    id: 2,
    logo: "./images/sum_bing.jpg",
    image: "./images/logo_bing.png",
    title: "빙그레",
    desc: "빙그레 홈페이지 - css를 활용해 반응형, 애니메이션을 활용한 페이지입니다.",
    site: "https://eunki0916.github.io/pf1/",
  },
  {
    id: 3,
    logo: "./images/sum_hyundai.jpg",
    image: "./images/logo_hyundaicard.svg",
    title: "현대카드",
    desc: "현대카드 홈페이지 - 현재 자주사용하는 카드로 css를 배웠던 것을 활용하고, 약간의 Javascript를 활용해 마우스 이벤트를 연습한 페이지입니다.",
    site: "https://eunki0916.github.io/pf4/",
  },
  {
    id: 4,
    logo: "./images/sum_tway.jpg",
    image: "./images/logo_tway.png",
    title: "티웨이",
    desc: "티웨이 홈페이지 - 여행갈때마다 자주 이용했던 회사로, 예약하는 곳을 보딩패스처럼 해보면 어떨까 싶어 변경해보았습니다.",
    site: "https://eunki0916.github.io/tway/",
  },
  {
    id: 5,
    logo: "./images/sum_ourhome.jpg",
    image: "./images/logo_ourhome.png",
    title: "아워홈",
    desc: "아워홈 홈페이지 - 부트스트랩과 슬릭라이브러리를 공부하면서 연습한 페이지입니다.",
    site: "https://eunki0916.github.io/ourhome/",
  },
  {
    id: 6,
    logo: "./images/tiretechbig.png",
    image: "./images/logo_tiretech.png",
    title: "타이어테크",
    desc: "타이어테크 - jquery를 공부하면서 반응형 웹사이트 연습한 페이지입니다.",
    site: "https://eunki0916.github.io/tiretech/",
  },
  {
    id: 7,
    logo: "./images/sum_kakao.jpg",
    image: "./images/logo_kakaoshop.png",
    title: "카카오프렌즈샵",
    desc: "카카오프렌즈샵 - jquery를 공부하면서 모바일형 웹사이트를 연습한 페이지입니다.",
    site: "https://eunki0916.github.io/kakaoFriends/",
  },
  {
    id: 8,
    logo: "./images/RTodoListbig.png",
    image: "./images/logo-todo.png",
    title: "React TodoList",
    desc: "React 공부하면서 만든 TodoList 페이지입니다.",
    site: "https://eunkitodolist.netlify.app/",
  },
  {
    id: 9,
    logo: "./images/rockbig.png",
    image: "./images/logo_rock.png",
    title: "가위바위보",
    desc: "두번째 React 프로젝트로 가위바위보를 하는 페이지입니다. ",
    site: "https://hrocksissor.netlify.app/",
  },

  {
    id: 10,
    logo: "./images/VTodoListbig.png",
    image: "./images/logo-todo.png",
    title: "Vue TodoList",
    desc: "Vue를 공부하면서 만든 TodoList 페이지입니다.",
    site: "https://vuetodos93.netlify.app/",
  },
  {
    id: 11,
    logo: "./images/pwabig.png",
    image: "./images/logo_pwa.png",
    title: "pwa 프로젝트",
    desc: "pwa를 사용해보기 위한 프로젝트입니다.",
    site: "https://eunki0916.github.io/pwa1/",
  },
  {
    id: 12,
    logo: "./images/H&MBig.png",
    image: "./images/logo_h&m.png",
    title: "H&M",
    desc: "세번째 React 프로젝트로 H&M 쇼핑몰 사이트입니다.",
    site: "https://hm0916.netlify.app/",
  },
];

export default img;
